### PR TITLE
Add sudo commands to readme

### PR DESCRIPTION
**Pull request by jamesgol**
#### Details

Necessary unless you run everything as root.

### CODE REVIEW

**Comment by moloch--** [comment]
These commands should not require root.

**Comment by moloch--** [comment]
Though I guess it depends if you're on MacOS or Linux (MacOS the npm -g directory is per user).

**Review by moloch-- — APPROVED** [review]

**Comment by rkervella** [comment]
Ugh this is a bad idea, just set a default directory that is writeable: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by moloch--** [comment]
It's just the readme hehe, I'm not too worried.

**Comment by jamesgol** [comment]
Hah, so much controversy.  Obviously you figured out I'm on Linux, didn't realize it'd be different elsewhere.  I'm not really a node fan, so I actually had to install npm and a bunch of stuff to try this out and the version bundled with my distro isn't compatible so I haven't even gotten to the finish line yet.

**Pull request merged**
